name: Cypress Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 coverage
          if [ -f requirements.txt ]; then 
            pip install -r requirements.txt;
          fi
        working-directory: "backend"

      - name: Start Backend Server
        run: |
          python main.py

      - name: Esecuzione dei test di Cypress
        run: |
          cd frontend
          npm install
          npm run serve &
          sleep 10  
          npm run cypress:run

      - name: Upload dei risultati dei test di Cypress
        uses: actions/upload-artifact@v2
        with:
          name: cypress-results
          path: frontend/cypress/videos


      

