name: Python WebApp

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Installazione Dipendenze
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Installazione Node.js and NPM
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Installazione Vue CLI
      run: |
        npm install -g @vue/cli

    - name: Installazione Dipendenze Bootstrap
      run: |
        npm install jquery popper.js

    - name: Installazione Vue.js dependencies
      run: |
        cd frontend
        npm install
        cd ..
    
    - name: Linting Codice Python (Flake8)
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Test Python
      run: |
        cd backend
        pytest

    - name: Build Unit Test
      run: |
        cd frontend
        npm run test:unit
        cd ..

    - name: Build FrontEnd
      run: |
        cd frontend
        npm run build
        cd ..

    - name: Lint FrontEnd
      run: |
        cd frontend
        npm run lint
        cd ..

    #- name: E2E Test
      #run: |
        #cd frontend
        #npm run test:e2e
        #cd ..
    
