name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 coverage
          if [ -f requirements.txt ]; thes pip install -r requirements.txt; fi
        working-directory: "backend"

      - name: Linting Codice Python (Flake8)
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: Run Python tests and generate coverage report
        run: |
          coverage run -m unittest discover -s tests/backend/ -p "test_*.py"
          coverage xml -o tests/backend/coverage.xml

      - name: Upload backend coverage report to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: tests/backend/coverage.xml
          flags: python
          name: backend-coverage


  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Installazione Node.js and NPM
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Installazione Vue CLI
        run: |
          npm install -g @vue/cli

      - name: Installazione Dipendenze Bootstrap
        run: |
          npm install jquery popper.js
      - name: Installazione Vue.js dependencies
        run: |
          npm install

      - name: Build Unit Test
        run: |
          cd tests/frontend
          npm run test:unit
      - name: Build FrontEnd

        run: |
          cd frontend
          npm run build
          
      - name: Linting Codice Vue.js
        run: |
          cd frontend
          npm run lint

      - name: Run Vue.js tests and generate coverage report
        run: |
          cd frontend
          npx jest --coverage

      - name: Upload frontend coverage report to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: frontend/coverage/lcov.info
          flags: frontend
          name: frontend-coverage
