name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 coverage
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run Python tests and generate coverage report
      run: |
        coverage run -m unittest
        coverage xml -o tests/results/coverage.xml
    - name: Installazione Node.js and NPM
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: Installazione Vue CLI
      run: |
        npm install -g @vue/cli
    - name: Installazione Dipendenze Bootstrap
      run: |
        npm install jquery popper.js
    - name: Installazione Vue.js dependencies
      run: |
        cd frontend
        npm install
        cd ..
    - name: Linting Codice Python (Flake8)
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test Python
      run: |
        cd tests/backend
        python -m unittest discover
        cd ..
    - name: Build Unit Test
      run: |
        cd tests/frontend
        npm run test:unit
    - name: Run Vue.js tests and generate coverage report
      run: |
        cd frontend
        npx jest --coverage
        cd ../..
    - name: Build FrontEnd
      run: |
        cd frontend
        npm run build
        cd ..
    - name: Linting Codice Vue.js
      run: |
        cd frontend
        npm run lint
        cd ..
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v4.0.1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: |
          backend/coverage.xml
          frontend/coverage/lcov.info # Aggiungi il percorso del report di copertura del frontend
        flags: python,frontend # Flags opzionali, utili per separare i report di copertura
        name: backend-coverage,frontend-coverage # Nomi opzionali, utili per separare i report di copertura
